### ISSUE TITLE
Add a command to fetch a random assigned easy issue

### ISSUE THREAD

**Issue by jdm** [servo/crowbot#35]
Specifically, I'd like to say something like "crowbot: what issue should I poke?" and get back a random issue that:
* either has the `E-easy` or `E-less easy` label applied
* has the `C-assigned` label applied
* has not been updated in at least 14 days
This should be possible to do using the existing `findIssue` function by passing the appropriate github API arguments (see the command for reviewing a PR for an example).

**Comment by perlun** [comment]
I guess we could close this one now that #39 is merged?

**Comment by jdm** [comment]
Yes, thanks.
