### ISSUE TITLE
Make crowbot testable

### ISSUE THREAD

**Issue by jdm** [servo/crowbot#37]
There have been some regressions recently because crowbot has grown organically and it's hard to test everything. We should refactor the bot to separate the interaction with the IRC library from the actual handlers, which would allow us to write automated tests that verify that everything behaves as expected. I imagine the handler function could accept a `say` argument which would be a function to be called in place of `bot.say` and `bot.act`. For the tests this could just append to an array, while for the real bot it would redirect to the appropriate methods of `bot`.

**Comment by bobthekingofegypt** [comment]
Can I pick this up?

**Comment by jdm** [comment]
@bobthekingofegypt Please do!

**Comment by bobthekingofegypt** [comment]
I made a start on this tonight.  I've created an early pull request, I'm not sure if you had plans or opinions on implementation.  

I've just gone with mocha and sinon, shuffled the code around a bit to make it easier to test in its current state.

I'll just go through the method adding tests for all conditions if you are happy.

**Comment by jdm** [comment]
See #41 for the initial implementation here.

**Comment by jdm** [comment]
#41 was merged.
