### ISSUE TITLE
Handle issue/PR links of the form `servo/saltfs#123`

### ISSUE THREAD

**Issue by aneeshusa** [servo/crowbot#55]
Crowbot currently will turn issue references like #123 (and £123) into links to the main Servo repo. It would be nice if this also worked for other repositories since we use a bunch of repos, with the syntax in the issue title.

**Comment by jdm** [comment]
https://github.com/servo/crowbot/blob/d6785d9b9ee5b2e6de86caa9d57804cfde171da9/server.js#L110-L143 is the code that watches for special links right now.
