### ISSUE TITLE
Require an argument for the `explain` command

### ISSUE THREAD

**Issue by jdm** [servo/crowbot#60]
This will prevent it being misused in attempts to learn more about how the bot works. We should just silently ignore anything like `<user> crowbot: explain`.

**Comment by jdm** [comment]
We should add an automated test for this - call the `handler` function, then check that the `say` array is empty.

**Comment by karan1276** [comment]
@jdm Could you tell me how to go about this? 😄

**Comment by jdm** [comment]
@karan1276 [This code](https://github.com/servo/crowbot/blob/7801c8f56ada5563b0865b6733c06c8d72302d53/server.js#L300) controls what happens when the bot sees an explain message. Is that what you're looking for?

**Comment by karan1276** [comment]
Wow, thanks a lot 👍

**Comment by karan1276** [comment]
@jdm i don't know if i should mention this here, but i just sent you mail, did you read it?

**Comment by jdm** [comment]
I don't appear to have received any emails from your email address.

**Comment by karan1276** [comment]
@jdm can i have your email id?

**Comment by karan1276** [comment]
@jdm when i run "npm install" i get some make file error, any clue why?

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)

**Comment by jdm** [comment]
I do not :(

**Comment by karan1276** [comment]
@jdm no problem, ill look into it.
