### ISSUE TITLE
Distinguish between PR and issue bare numbers

### ISSUE THREAD

**Issue by notriddle** [servo/crowbot#63]
When you type a whole link into IRC, this happens

    you> https://github.com/servo/servo/pull/14707
    crowbot> PR #14707: Pipeline documentation comments - https://github.com/servo/servo/pull/14707

But if you just type the number in, you get

    you> #14707
    crowbot> Issue #14707: Pipeline documentation comments - https://github.com/servo/servo/pull/14707

This is dumb. Crowbot has enough information to tell that it's a PR, based on the URL it put in to IRC (also, the GitHub API has a `"pull_request"` JSON key, so crowbot really doesn't need to parse the URL at all).

**Comment by jdm** [comment]
Fixed by #66.
