### ISSUE TITLE
Make noise when a build machine's job is taking longer than 1 hour

### ISSUE THREAD

**Issue by jdm** [servo/crowbot#75]
We can learn about current build jobs on our machines by fetching  http://build.servo.org/json/slaves?as_text=1. One example shows that sevo-linux-cross3 has been running for more than 2 hours: https://gist.github.com/jdm/ae1be5ef10ef308f9fdc93856a0515e0 . We should query this information every 30 minutes and squawk loudly if any build machine is stuck.

**Comment by carlosmcgregor** [comment]
Hello, @jdm ! Can I take over this issue?

**Comment by jdm** [comment]
Please do! Ask questions if anything is unclear!

**Comment by jdm** [comment]
@carlosmcgregor Have you made any progress with this?

**Comment by carlosmcgregor** [comment]
Thank you for your patience! I have my test IRC server running and I have been playing around with crowbot commands. I am also reviewing its code so that I do not add unnecessary lines. I hope to be done by the end of the weekend, if that's alright.

**Comment by carlosmcgregor** [comment]
@jdm Just making sure: the alert needs to go off for builds that have past their ETA.

**Comment by jdm** [comment]
@carlosmcgregor I would say if a build is >30 minutes past the ETA, it would be worth alerting about the fact.

**Comment by carlosmcgregor** [comment]
@jdm I am pretty much done, but I am missing the squawking part. Could you please hint me in the direction of how to send sounds via IRC? I read about the /sound command, but I could not find a resource talking about how to enact this via node-irc.

**Comment by jdm** [comment]
Sorry, by squawk I just meant send a message to the channel that gets attention.

**Comment by carlosmcgregor** [comment]
Oh okay! Sorry, I'm new to crowbot so I'm still getting used to the terms used here. Would this channel be #servo? Also, is it necessary for me to add test cases?

Sorry if I'm asking too many questions!

**Comment by jdm** [comment]
You can follow the example of [this code](https://github.com/servo/crowbot/blob/master/server.js#L529-L535) which uses the first channel from the configuration file as the target. And a test case would be nice to have, if it doesn't require too many awkward internal changes to support. This project uses mocha, and you can find the tests in tests/server.test.js, and run them with `npm test`.

**Comment by carlosmcgregor** [comment]
Thank you! That's the code I was using. I will be making a pull request right now.

**Comment by jdm** [comment]
This was fixed by #76 and #79.
