### ISSUE TITLE
Build time ETA is unreliable

### ISSUE THREAD

**Issue by jdm** [servo/crowbot#78]
cc @carlosmcgregor

We're seeing notifications for build jobs which have only started <10 minutes ago, so it appears the ETA cannot be trusted at all. We should instead look at the start time for the running build and notify the channel if it has been running for more than 90 minutes. Additionally, we should ensure that our time comparisons take place in the PST timezone, since there's no guarantee that the current time for the bot matches the time for the build log.

**Comment by jdm** [comment]
This leads to fun messages like: `<crowbot> servo-mac1 is overdue! (build started in 16 minutes)`

**Comment by carlosmcgregor** [comment]
That is sure a fun message!

Could we make a combination of both ETA and start time? Only check ETA > .5 after 90 minutes have passed.

**Comment by jdm** [comment]
We could, but it's not clear to me whether that would be a meaningful improvement. I was watching the ETA data shift wildly over the course of an unexceptional run, so I don't really know what it's actually supposed to tell us.

**Comment by jdm** [comment]
Additionally, http://trac.buildbot.net/ticket/540 says that the ETA is "badly inaccurate" in the 0.8.x versions, and we're using 0.8.12 according to https://github.com/servo/saltfs/blob/master/buildbot/master/init.sls#L9.

**Comment by carlosmcgregor** [comment]
Thank you for the comprehensive explanation on why ETA is not working out. I will be sticking to start times for the patch.

**Comment by carlosmcgregor** [comment]
Since we will be comparing UNIX timestamps, there will be no need to implement timezones. Please correct me if I am wrong.

There are no running builds now in the dead of the night, so I will be testing this tomorrow before doing the pull request.

**Comment by jdm** [comment]
Let's see if the results make sense without any timezone logic.
